### PR TITLE
README, LICENSE, CONTRIBUTING Markdown Files

### PR DESCRIPTION
**Pull request by jevenson**
#11 

@TimHess This is what I came up with, please let me know if you would like changes made or if you would like to use a different license.

### CODE REVIEW

**Comment by jevenson** [comment]
#11

**Review by TimHess — APPROVED** [review]
Looks great, thanks!

**Comment by jevenson** [comment]
@TimHess thoughts on Wiki vs Contributing file? I'm not sure what is more common. Open to either way.

**Comment by TimHess** [comment]
I don't have a strong opinion, but given then choice between the two, I can see where putting it in the wiki makes a bit more sense

**Pull request merged**
