### PR TITLE
Add cta to announce CWITC conference.

### PR DESCRIPTION
**Pull request by daniel-packard**
Is this CTA too in your face? As always, feedback from someone with better frontend skills and design sense is welcome 😉 

Color scheme hijacked from cwitc site.

image

### CODE REVIEW

**Comment by jevenson** [comment]
What do you think about moving it into a jumbotron above the social icons?

https://v4-alpha.getbootstrap.com/components/jumbotron/

**Comment by daniel-packard** [comment]
That works for me - same color, layout and width, but centered in a jumbo Tron?

**Comment by daniel-packard** [comment]
Or... Same thing _as_ a jumbotron? 🤔

**Comment by jevenson** [comment]
Maybe we could lift the picture of downtown from the CWITC site too, would have to check with someone for copyright. @TimHess would you know about this?

I like the colors yeah! If you check out the first example on the bootstrap docs, maybe make the button the red, and have the picture in the background? idk that might get weird with the text on top of it.

Mainly I thought the jumbotron would match the cards for social better and be larger so people would see it.

But now I'm thinking that might be where we would want presentations to be?

Maybe we just complete this PR now, and come up with a design for the page including all the other planned enhancements?

**Comment by daniel-packard** [comment]
Or just a jumbotron.. sorry to spam the comments ☹️

**Comment by daniel-packard** [comment]
Closing as-is, followed by some upfront design​ works for me 👍

**Comment by jevenson** [comment]
Sounds good, ill review the code in a sec... in the middle of an Uncharted 4 game ahaha

**Review by jevenson — APPROVED** [review]

**Pull request merged**
